title: "Talking About Doing"
description: "A blog about software engineering, continuous learning, and story-telling."
url: "https://TalkingAboutDoing.com"
baseurl: ""
author: "Talking About Doing"
email: "chris@talkingaboutdoing.com"
buttondown_username: "ccrolf"

markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - "*.sh"
