title: "Talking about doing"
description: "Software engineering and continuous learning."
url: "https://talkingaboutdoing.com"
baseurl: ""
author: "Chris"
email: "chris@talkingaboutdoing.com"
buttondown_username: "ccrolf"

markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - "*.sh"
